let modelsJson = [

    {id:1, name:'Caneca Din Djarin', img:'img/din.png', price:[50.00, 52.00, 54.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Din Djarin (Pedro Pascal) é um guerreiro solitário que trabalha como caçador de recompensas em The Mandalorian. Ele embarca em uma jornada pelas terras esquecidas do luar, logo após a queda do Império e antes da formação da lendária Primeira Ordem.<br>\n<br>\n <b> Capacidade até 320ml.<br>\n Resistente a micro-ondas e lava-louças.<br>\n 10cm de altura.<br>\n 12cm de comprimento (contando com uma alça).<br>\n </b>    '},
    {id:2, name:'Camiseta Death Note', img:'img/natsucaneca.png', price:[50.00, 52.00, 54.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Natsu é despreocupado e irresponsável por natureza, e, apesar de suas brigas constantes com os outros membros da Fairy Tail, ele é um amigo extremamente leal e protetor. Ele está disposto a descer lutando por seus amigos. Natsu tem uma mente simples, e muitas vezes, sua solução para os problemas envolvem a violência.<br><br>\n<b>Capacidade: 325ml <br>\n Comprimento: 12cm <br>\n Largura: 8cm <br>\n Altura: 9,5cm <br>\n </b>    '},
    {id:3, name:'Caneca Goku', img:'img/goku.png', price:[50.00, 52.00, 54.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Natsu Dragneel é o protagonista  da história e membro da guilda Fairy Tail, buscando fazer missões e descobrindo novos desafios e até mesmo sua origem, ele e seu amigo Happy junto com Lucy, uma maga, estão sempre em busca de novas aventuras.'},
    {id:4, name:'Camiseta One Piece', img:'img/one-1.png', price:[50.00, 52.00, 54.00], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'One Piece é uma série de mangá escrita e ilustrada por Eiichiro Oda, composto atualmente por 1044 capítulos , é uma das obras mais vendidas da história , superando Batman, onde introduz a história do pirata Monkey D. Luffy a achar seu bando e buscar o tesouro One Piece. '},
    {id:5, name:'Camiseta Roronoa Zoro', img:'img/one-2.png', price:[50.00, 52.00, 54.00], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Um dos personagens mais aclamados do anime One Piece, Roronoa Zoro, primeiro companheiro do protagonista Luffy Chapéu de Palha , é o braço direito do protagonista , sendo extremamente conhecido pela sua força e um dos personagens mais poderosos da série.'},
    {id:6, name:'Camiseta Levi Ackerman', img:'img/levi.png', price:[50.00, 52.00, 54.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Levi é um dos personagens mais adorados pelos fãs da obra de Shingeki no Kyojin, ele possui o cargo de capitão , vindo de um clã bem poderoso, sempre mostrado como o melhor guerreiro da série , ele é praticamente uma lenda viva, assim sendo ao decorrer da série  ele ganhou o apelido de Matador de Titãs.'},
    {id:7, name:'Camiseta Ichigo', img:'img/ichigo-1.png', price:[50.00, 52.00, 54.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71	Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Kurosaki Ichigo é o protagonista da série bleach , onde se torna um shinigami (deus da morte) e em busca de proteger sua cidade e seus companheiros de qualquer tipo de assombração, busca sempre uma maneira de lidar com as diversas situações.'},
    {id:8, name:'Camiseta Escanor', img:'img/escanor.png', price:[50.00, 52.00, 54.00], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Escanor é um dos personagens mais aclamados pelos fãs da obra de Nanatsu no Taizai, ele faz parte do grupo dos 7 pecados capitais e representa o pecado do Orgulho, conhecido pela sua força e orgulho ele se torna um dos principais personagens da série.'},
    {id:9, name:'Camiseta Naruto', img:'img/naruto.png', price:[50.00, 52.00, 54.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Uzumaki Naruto é o protagonista da série Naruto, onde eles cresce como um menino órfão no mundo ninja, sempre muito temperamental, ele busca ser o melhor ninja e se tornar Hokage (líder da vila) e cuidar de todos os outros.'} 

];