let modelsJson = [

    {id:1, name:'Caneca Goku', img:'img/cagoku.png', price:[40.00, 40.00, 40.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Goku ou Son Goku, nascido Kakarotto é o protagonista das franquias Dragon Ball. Ele é neto adotivo de Vovô Gohan, filho de Bardock e Gine, onde desde sua infância seu objetivo sempre foi ficar mais forte e se divertir com as lutas para se tornar o melhor guerreito possível. '},
    {id:2, name:'Caneca Death Note', img:'img/cadeath.png', price:[40.00, 40.00, 40.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Death Note é uma série de mangá escrita por Tsugumi Ohba e ilustrada por Takeshi Obata que ficou muito famoso desde os anos 2005, o death note é um caderno que permite o usuário o poder de matar uma pessoa, quando e como ela vai morrer.'},
    {id:3, name:'Caneca Natsu', img:'img/canatsu.png', price:[40.00, 40.00, 40.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Natsu Dragneel é o protagonista  da história e membro da guilda Fairy Tail, buscando fazer missões e descobrindo novos desafios e até mesmo sua origem, ele e seu amigo Happy junto com Lucy, uma maga, estão sempre em busca de novas aventuras.'},
    {id:4, name:'Caneca One Piece', img:'img/oneca.png', price:[40.00, 40.00, 40.00], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'One Piece é uma série de mangá escrita e ilustrada por Eiichiro Oda, composto atualmente por 1044 capítulos , é uma das obras mais vendidas da história , superando Batman, onde introduz a história do pirata Monkey D. Luffy a achar seu bando e buscar o tesouro One Piece. '},
    {id:5, name:'Caneca Roronoa Zoro', img:'img/caone.png', price:[40.00, 40.00, 40.00], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Um dos personagens mais aclamados do anime One Piece, Roronoa Zoro, primeiro companheiro do protagonista Luffy Chapéu de Palha , é o braço direito do protagonista , sendo extremamente conhecido pela sua força e um dos personagens mais poderosos da série.'},
    {id:6, name:'Caneca Levi Ackerman', img:'img/calevi.png', price:[40.00, 40.00, 40.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Levi é um dos personagens mais adorados pelos fãs da obra de Shingeki no Kyojin, ele possui o cargo de capitão , vindo de um clã bem poderoso, sempre mostrado como o melhor guerreiro da série , ele é praticamente uma lenda viva, assim sendo ao decorrer da série  ele ganhou o apelido de Matador de Titãs.'},
    {id:7, name:'Caneca Ichigo', img:'img/caichigo.png', price:[40.00, 40.00, 40.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71	Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Kurosaki Ichigo é o protagonista da série bleach , onde se torna um shinigami (deus da morte) e em busca de proteger sua cidade e seus companheiros de qualquer tipo de assombração, busca sempre uma maneira de lidar com as diversas situações.'},
    {id:8, name:'Caneca Escanor', img:'img/caescanor.png', price:[40.00, 40.00, 40.00], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Escanor é um dos personagens mais aclamados pelos fãs da obra de Nanatsu no Taizai, ele faz parte do grupo dos 7 pecados capitais e representa o pecado do Orgulho, conhecido pela sua força e orgulho ele se torna um dos principais personagens da série.'},
    {id:9, name:'Caneca Naruto', img:'img/canaruto.png', price:[40.00, 40.00, 40.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Uzumaki Naruto é o protagonista da série Naruto, onde eles cresce como um menino órfão no mundo ninja, sempre muito temperamental, ele busca ser o melhor ninja e se tornar Hokage (líder da vila) e cuidar de todos os outros.'} 

];