let modelsJson = [

    {id:1, name:'Figura de ação Hades', img:'img/hades.png', price:[1949, 1949, 1949], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Hades, conhecido como rei dos mortos, é o maior antagonista da série "Os Cavaleiros do Zodíaco" e tem o desejo de tomar a Terra.<br><br>\n <b>Tamanho: 18 cm<br>\nMaterial: PVC, ABS e Die-cast.<br>\n Tipo: articulado.</b>'},
    {id:2, name:'Figura de ação Surfista Prateado', img:'img/surfista.png', price:[1429, 1429, 1429], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'O Surfista prateado vivia no planeta de Zenn-La. o Surfista ficou encarregado de buscar planetas capazes de oferecer energia a Galactos. Afim de poupar mortes desnecessárias, ele encontrava apenas planetas sem habitantes.<br><br>\n <b>Tamanho: 65 cm.<br>\nMaterial: Polystone.<br>\n</b>'},
    {id:3, name:'Funko Pain', img:'img/pain.png', price:[179, 179, 179], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Pain acabou se tornando órfão pelo conflito, a segunda guerra mundial Shinob, e se uniu com seus amigos órfãos de guerra para formar a Akatsuki, uma organização cujos objetivos foram parar os ciclos infinitos de morte.<br><br>\n <b>Tamanho: 17 cm.<br>\n Material: Vinil.<br>\n</b>'},
    {id:4, name:'Figura de ação Levi Ackerman', img:'img/filevi.png', price:[1429, 1429, 1429], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'levi ackerman é um personagem do mangá Shingeki no Kyojin. Ele é Capitão do grupo de Pesquisa. Levi morava no submundo mas conseguiu subir para as muralhas onde teve a oportunidade de mostrar seu potencial, matando Titãs.<br><br>\n <b>Tamanho: 28 cm.<br>\n Material:PVC.<br>\n</b>'},
    {id:5, name:'Figura de ação Spider-man vs Venom', img:'img/spider.png', price:[6649.99, 6649.99, 6649.99], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Peter Park visita um laboratório e acaba sendo mordido por uma aranha radioativa, onde ele ganha seus super poderes. O Venom é um simbionte, uma raça alienígena, ele precisa de um hospedeiro para viver, ele encotra o Peter, mas acaba tendo desavenças e vira inimigo.<br><br>\n <b> amanho: 58 cm.<br>\n Material: Polystone.<br>\n</b>'},
    {id:6, name:'HQ Super-man #1', img:'img/super.png', price:[27185.290, 27185.290, 27185.290], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'O personagem nasceu no planeta fictício Krypton e tinha o nome de Kal-El. Foi enviado à Terra por seu pai cientista, Jor-El, momentos antes de Krypton explodir. Duas pessoas o encontraram e o criou, com o passar do tempo descobriam que ele tinha capacidades sobre-humanas.<br><br>\n <b>Tamanho: 55 cm.<br>\n Lançamento:1938.<br>\n</b>'},
    {id:7, name:'HQ Batman #1', img:'img/batman.png', price:[4358.630, 4358.630, 4358.630], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71	Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Ano um começa com o retorno do jovem Bruce Wayne à sua cidade natal, após um longo período de viagens pela Europa e Ásia. Viagens estas que Wayne aproveitou para adquirir e aperfeiçoar todas as habilidades e conhecimentos necessários para seu objetivo: o combate ao crime.<br><br>\n <b>Dimensões: 26 X 17 cm.<br>\n Lançamento: 1940.<br>\n</b>'},
    {id:8, name:'Pikachu Illustrator', img:'img/pikachu.png', price:[4618.980, 4618.980, 4618.980], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Pikachu é um pokemon onde ele e seu treinador Ash Ketchum vivem aventuras e desafios. A carta Pikachu Illustrator foi dada em janeiro de 1998 aos vencedores do Concurso de Ilustração da revista CoroCoro.<br>\n <b><br>\n MINT: 9.<br>\nLançamento: 1998.<br>\n</b>'},
    {id:9, name:'Figura de ação Iron Man', img:'img/ferro.png', price:[6849, 6849, 6849], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Tony Stark, um bilionário apaixonado por tecnologia, cria uma armadura de última geração para combater xcv crimes. Conhecido como Homem de Ferro.<br><br>\n <b>Tamanho: 50 cm.<br>\n Material: Polystone.<br>\n</b>'} 

];