let modelsJson = [

    {id:1, name:'Almofada Goku - Dragon Ball', img:'img/almofada.png', price:[39.99, 39.99, 39.99], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Son Goku o protagonista da saga Dragon Ball. O menino com rabo de macaco com uma força sobre-humana, com o decorrer da série descobrimos que ele e faz parte de umas das raças mais poderosas do universo.<br><br>\n <b>Dimensões: 40cm x 40cm.<br>\n Largura: 10cm.<br>\n</b>'},
    {id:2, name:'Caderno-Death Note', img:'img/caderno.png', price:[29.99, 29.99, 29.99], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Um estudante chamado Light Yagami encontra um caderno que caiu do céu. Em sua capa está escrito Death note, onde o portador desse carderno tem o poder de matar qualquer pessoa simplemeste escrevendo o seu nome completo. O estudante descobrindo esse poder começa a eliminar criminosos e pessoas que escapam da justiça.<br><br>\n <b>Altura: 20 cm.<br>\n Largura: 15 cm.<br>\n Páginas: 100.<br>\n</b>'},
    {id:3, name:'Tapete Equipe 7 - Naruto', img:'img/tapete.png', price:[119.90, 119.90, 119.90], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'O Time Kakashi, mais comumente conhecido como Time 7, foi uma equipe de Konohagakure formado sob a liderança de Kakashi Hatake. Seus membros originais são Naruto Uzumaki, Sasuke Uchiha e Sakura Haruno.<br><br>\n <b>Dimensões: 1,00m x 1,3m.<br>\n Acabamento: Bainha em catraca com 2 agulhas.<br>\n</b>'},
    {id:4, name:'Porta pipoca - Akatsuki', img:'img/pipoca.png', price:[69.90, 69.90, 69.90], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'A Akatsuki tinha o objetivo original de alcançar a paz e por um fim nas guerras. Mas com a morte de um dos fundadores o objetivo foi mudado e assim o caos nas nações começou.<br><br>\n <b>Altura: 13.00 cm.<br>\n Largura: 35.00 cm.<br>\n Comprimento: 40.00 cm.<br>\n</b>'},
    {id:5, name:'Iluminaria Mjolnir - Thor', img:'img/iluminaria.png', price:[49.90, 49.90, 49.90], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'O martelo de Thor, Mjolnir. Na mitologia, o martelo de Thor é um símbolo de força e poder, com o qual o deus é capaz de controlar a energia dos trovões<br><br>\n <b>Altura: 45 cm.<br>\n Largura: 11 cm.<br>\n Comprimento: 23 cm. <br>\n Led: 3 cores diferentes.<br>\n</b>'},
    {id:6, name:'Star Wars Relogio', img:'img/relogio.png', price:[149.90, 149.90, 149.90], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'A princesa Leia é mantida refém pelas forças imperiais comandadas por Darth Vader. Luke Skywalker e o capitão Han Solo precisam libertá-la e restaurar a liberdade e a justiça na galáxia.<br><br>\n <b>Polegadas: 18.<br>\n Material: PVC.<br>\n</b>    '},
    {id:7, name:'Mouse Pad - Giyu Tomioka', img:'img/mousepad.png', price:[69.70, 69.70, 69.70], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71	Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Giyu Tomioka conhecido por ser um dos hashiras mais forte, domina a técnica de respiração da água. Além das dez formas tradicionais de respiração da água, Tomioka criou uma 11ª forma.<br><br>\n <b>Dimenções: 90cm x 40cm.<br>\n Espessura: 3cm.<br>\n</b>'},
    {id:8, name:'Pelúcia Armin - Attack of Titans', img:'img/pelucia.png', price:[49.99, 49.99, 49.99], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Armin foi um dos melhoras amigos de infância de Eren Yeager e Mikasa Ackerman. Se destacava por conta de sua inteligência e raciocínio durante as missões.<br><br>\n <b> Comprimento: 35cm.<br>\n Largura: 15cm.<br>\n Material: 100% Poliéster.<br>\n</b>    '},
    {id:9, name:'Coberta - My hero academia', img:'img/coberta.png', price:[169.99, 169.99, 169.99], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Em um mundo onde (quase) todas as pessoas possuem superpoderes, o Izuku Midoriya teve a infelicidade de nascer sem nenhum poder. Grande fã do sorridente All Might, Deku, como é chamado pelos colegas, sofre com a frustração de saber que jamais terá uma individualidade especial para que possa se tornar, assim como seu grande ídolo, em um defensor dos fracos e oprimidos.<br><br>\n <b> Largura: 260.00 cm.<br>\n Comprimento: 260.00 cm.<br>\n Composição: Microfibra Premium.<br>\n</b>'} 

];