let modelsJson = [

    {id:1, name:'Manga Demon Slayer', img:'img/demon.png', price:[1199.00 , 1199.00, 1199.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'No Japão da era Taisho, o bondoso Tanjiro Kamado ganha a vida vendendo carvão. Mas sua vida pacífica é destruída quando um demônio massacra toda a sua família. Sua irmãzinha Nezuko é a única sobrevivente, mas ela mesma se transformou em um demônio! Tanjiro parte em uma jornada perigosa para encontrar uma maneira de devolver sua irmã aonormal e destruir o demônio que arruinou sua vida.<br><br>\n <b>Volume: 1 ao 23.<br>\n Altura: 15.00 cm.<br>\n Largura: 22.00 cm.<br>\n Comprimento: 10.00 cm<br>\n Peso: 9,2 g. <br>\n</b>'},
    {id:2, name:'Manga Nanatsu No Taizai', img:'img/Nanatsu.png', price:[112.7, 112.7, 112.7], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Após 10 anos, os Cavaleiros Sagrados do Reino Liones se juntaram para destronar o seu atual rei, bem como para assumirem o poder. Uma das princesas do reino, Elizabeth, consegue fugir e segue em busca dos Nanatsu no Taizai, na esperança de que eles possam ajudar a tirar os Cavaleiros Sagrados do poder.<br><br>\n <b> Volume: 1 ao 7.<br>\n Altura: 15.00 cm.<br>\n Largura: 22.00 cm.<br>\n Comprimento: 10.00 cm.<br>\n Peso: 2,8 g. <br>\n</b>'},
    {id:3, name:'Manga One Piece', img:'img/one.png', price:[218.48, 218.48, 21.48], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'One Piece segue a história de um grupo de piratas liderado por Monkey D. Luffy. O garoto, que possui um corpo elástico, pretende se tornar o Rei dos Piratas e para isso deve encontrar o One pPiece, tesouro misterioso capaz de torná-lo imbatível, segundo as lendas.<br><br><b>\n Volume: 1 ao 8. <br>\n Altura: 15.00 cm. <br>\n Largura: 22.00 cm. <br>\n Comprimento: 10.00 cm. <br>\n Peso: 3,2 g. </b>'},
    {id:4, name:'Manga One Punch-Man', img:'img/punch.png', price:[336.15, 336.15, 336.15], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'One Punch-Man conta a história de Saitama, um super-herói extremamente poderoso, que se entediou com a ausência dos desafios nas suas lutas contra o mal e procura encontrar um oponente digno.<br><br>\n <b>Volume: 1 ao 15.<br>\n Altura: 15.00 cm.<br>\n Largura: 22.00 cm.<br>\n Comprimento: 10.00 cm.<br>\n Peso: 6,100 g. <br>\n</b>'},
    {id:5, name:'Manga JoJo s', img:'img/jojo.png', price:[359.20, 359.20, 359.20], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'JoJo s conta a história da família Joestar, uma família cujos vários membros descobrem que estão destinados a derrubar inimigos sobrenaturais, tais como Dio Brando um vampiro semi-imortal, Yoshikage Kira um serial killer e Diavolo um líder de gangue usando poderes únicos que possuem.<br><br>\n <b>Volume: 40 ao 50. <br>\n Altura: 15.00 cm.<br>\n Largura: 22.00 cm.<br>\n Comprimento: 10.00 cm.<br>\n Peso: 4,2 g.<br>\n</b> '},
    {id:6, name:'Manga Banana Fish', img:'img/banana.png', price:[343.46, 343.46, 343.46], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Banana Fish, a história gira em torno de Ash Lynx, um líder de uma gangue em Nova York com apenas 17 anos. O nosso protagonista é frio e calculista e conforme a leitura você vai percebendo o quão aguçado é o seu senso de sobrevivência e quão forte ele é.<br><br>\n <b>Volume: 1 ao 7.<br>\n Altura: 15.00 cm.<br>\n Largura: 22.00. cm<br>\n Comprimento: 10.00 cm.<br>\n Peso: 3,5 g.<br>\n</b>'},
    {id:7, name:'Manga Vampire Knight', img:'img/vampire.png', price:[340.00, 340.00, 340.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71	Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Vampire Knight conta a história de Yuuki, uma estudante do colégio Cross, um internato de prestígio que divide alunos em dois grupos: A Classe dos Alunos de Dia, cujos alunos são humanos e todos usam uniformes escuros e a Classe dos Alunos Noturnos, constituídos por vampiros que usam uniformes claros.<br><br>\n <b>Volume: 1 ao 16.<br>\n Altura: 15.00 cm.<br>\n Largura: 22.00 cm.<br>\n Comprimento: 10.00 cm.<br>\n Peso: 7,2 g.<br>\n</b>'},
    {id:8, name:'Manga My Hero Academia', img:'img/hero.png', price:[354.00, 354.00, 354.00], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'All Might e Deku aceitam um convite para visitar a Ilha I, onde está acontecendo a exposição de tecnologia mais importante do mundo. Lá, eles lutam contra um vilão que invade o sistema de segurança e toma a ilha toda como refém.<br><br>\n <b>Volume: 1 ao 10.<br>\n Altura: 15.00 cm.<br>\n Largura: 22.00 cm.<br>\n Comprimento: 10.00 cm.<br>\n Peso: 4,2 g.<br>\n</b>'},
    {id:9, name:'Manga Bleach', img:'img/bleach.png', price:[539.16, 539.16, 539.16], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'O jovem Ichigo, depois de passar grande parte de sua vida vendo fantasmas, se torna um Shinigami, um ser sobrenatural capaz de controlar a morte.<br><br>\n <b>Volume: 1 ao 21.<br>\n Altura: 15.00 cm.<br>\n Largura: 22.00 cm.<br>\n Comprimento: 10.00 cm.<br>\n Peso: 8,4 g.<br>\n</b>'} 

];