let modelsJson = [

    {id:1, name:'Placa Decorativa - Scarlett', img:'img/Scarlett.png', price:[25.00, 25.00, 25.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Placa Decorativa - Somente Pessoal Autorizado Ou Scarlett <br><br>\n <b>Não precisa furar a parede e não empena se for exposta ao ar livre. Deixe a sua casa com a sua cara. <br><br>\n Medidas: 18cm x 23cm. <br><br>\n Fixação: Todas as placas possuem adesivo dupla face para aplicação em qualquer tipo de superfície lisa. <br>\n </b>'},
    {id:2, name:'Placa Decorativa - Gamer', img:'img/minerando.png', price:[25.00, 25.00, 25.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Placa Decorativa - Não perturbe gamer minerando. <br><br>\n <b>Não precisa furar a parede e não empena se for exposta ao ar livre. Deixe a sua casa com a sua cara. <br><br>\n Medidas: 18cm x 23cm. <br><br>\n Fixação: Todas as placas possuem adesivo dupla face para aplicação em qualquer tipo de superfície lisa. <br>\n </b>'},
    {id:3, name:'Placa Decorativa - Goku', img:'img/quagoku.png', price:[25.00, 25.00, 25.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Placa Decorativa - É mais de 8000 seu poder de batalha. <br><br>\n <b>Não precisa furar a parede e não empena se for exposta ao ar livre. Deixe a sua casa com a sua cara. <br><br>\n Medidas: 18cm x 23cm. <br><br>\n Fixação: Todas as placas possuem adesivo dupla face para aplicação em qualquer tipo de superfície lisa. <br>\n </b>'},
    {id:4, name:'Quadro Decorativo - Death Note, Light Yagami Kira', img:'img/quadeath.png', price:[40.00, 40.00, 40.00], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Quadro Decorativo Poster Anime Death Note Light Yagami Kira.<br><br>\n<b> Material: MDF 3MM de espessura. <br><br>\n Tamanho: 30cm x 20cm. <br><br>\n Acompanha fita dupla face para fixação na parede. <br><br>\n Imagem impressa em alta resolução com película protetora a prova d água e anti riscos.</b><br>\n'},
    {id:5, name:'Quadro Decorativo - 7 Pecados capitais, Escanor', img:'img/quaescanor.png', price:[40.00, 40.00, 40.00], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Quadro Decorativo Poster Escanor 7 Pecados Meliodas.<br><br>\n<b> Material: MDF 3MM de espessura. <br><br>\n Tamanho: 30cm x 20cm. <br><br>\n Acompanha fita dupla face para fixação na parede. <br><br>\n Imagem impressa em alta resolução com película protetora a prova d água e anti riscos.</b><br>\n'},
    {id:6, name:'Quadro Decorativo - Shingeki no Kyojin, Levi Ackerman', img:'img/qualevi.png', price:[40.00, 40.00, 40.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'Quadro Decorativo Poster Shingeki no Kyojin, Levi Ackerman.<br><br>\n<b> Material: MDF 3MM de espessura. <br><br>\n Tamanho: 30cm x 20cm. <br><br>\n Acompanha fita dupla face para fixação na parede. <br><br>\n Imagem impressa em alta resolução com película protetora a prova d água e anti riscos.</b><br>\n'},
    {id:7, name:'Quadro decorativo Dragon Ball Z', img:'img/quadragon.png', price:[70.00, 70.00, 70.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71	Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'05 peças. Tamanho total após a instalação de 115 cm de comprimento e 60 cm de altura 6 mm espessura. <br><br>\n<b> Acompanha fita dupla face para fixação na parede com impressão digital ecológica, de alta tecnologia, sem cheiro, proporcionando imagens de alta qualidade e durabilidade'},
    {id:8, name:'Quadro decorativo time 07 Naruto', img:'img/quanaruto.png', price:[70.00, 70.00, 70.00], sizes:['Largura:49	Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'03 peças. Tamanho total após a instalação de 95 cm de comprimento e 45 cm de altura 6 mm espessura. <br><br>\n<b> Acompanha fita dupla face para fixação na parede com impressão digital ecológica, de alta tecnologia, sem cheiro, proporcionando imagens de alta qualidade e durabilidade'},
    {id:9, name:'Quadro decorativo Harry Potter', img:'img/quaharry.png', price:[70.00, 70.00, 70.00], sizes:['Largura:49 Altura:68 Manga:20', 'Largura:53 Altura:71 Manga:20', 'Largura:57	Altura:72	Manga:22'], description:'04 peças. Tamanho total após a instalação de 20 cm de comprimento e 20 cm de altura 6 mm espessura. <br><br>\n<b> Acompanha fita dupla face para fixação na parede com impressão digital ecológica, de alta tecnologia, sem cheiro, proporcionando imagens de alta qualidade e durabilidade'} 

];